runtime: go112

handlers:
- url: /(.*\.js)$
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.json)$
  mime_type: application/json
  static_files: static/\1
  upload: static/(.*\.json)

- url: /
  secure: always
  script: auto
